### ISSUE TITLE
Error while activating Noice community plugin

### ISSUE THREAD

**Issue by MayukhSobo** [AstroNvim/astrocommunity#1255] opened 2024-10-31 10:58 UTC
### Checklist

- [X] I have searched through the AstroNvim documentation
- [X] I have searched through the existing issues of this project
- [X] I have searched the existing issues of plugins related to this issue
- [] I can replicate the bug with the minimal `repro.lua` provided below

### Neovim version (nvim -v)

0.10.2

### Operating system/version

macOS 15.0.1 24A348 arm64

### Terminal/GUI

Alacritty

### Describe the bug

I am new to vim and I am just staring out with AstroNVim. I am using Noice using the community plugin like following.

{ import = "astrocommunity.utility.noice-nvim"},

I am getting the following error message

```
vim.lsp.handlers["textDocument/signatureHelp"] has been overwritten by another plugin?

Either disable the other plugin or set `config.lsp.signature.enabled = false` in your **Noice** config.
  - plugin: nvim
  - file: /opt/homebrew/Cellar/neovim/0.10.2_1/share/nvim/runtime/lua/vim/lsp.lua
  - line: 1172
  - 
  ```

### Steps to Reproduce

Just install noice and start astro with any file.

### Expected behavior

The error should not come.

### Screenshots

![image](https://github.com/user-attachments/assets/62e989b5-568b-4ddd-8c80-4d66700e47ec)

**Can anyone tell me where to add this config? Or is there something else that I am doing wrong? I can understand that I have to add `config.lsp.signature.enabled = false` but I am not sure how or where!**

**Comment by Uzaaft** [comment] 2024-11-16 17:17
Not a bug, a user error. 

Can be fixed by overriding the opts in your config. See the astrocommunity readme for an example.

**Closed by Uzaaft** 2024-11-16 17:17 UTC
Labels: user error
