### ISSUE TITLE
pack/lua: luacheck is still reporting a 113 on undefined variable 'vim'

### ISSUE THREAD

**Issue by windowsrefund** [AstroNvim/astrocommunity#317] opened 2023-06-25 15:48 UTC
Saw the exact same behavior as described in #302 

Added the [mentioned .luacheckrc](https://github.com/AstroNvim/user_example/commit/8b8a9a035f3f409c95135d93abdada88d3a1ce3c) into my ~/.config/astronvim/lua/user directory.

Still seeing the errors as reported by luacheck.

**Comment by mehalter** [comment] 2023-06-25 15:51
Duplicate of #302, please keep discussion localized

**Closed by mehalter** 2023-06-25 15:51 UTC
