### ISSUE TITLE
All mappings of grugfar.nvim cannot be used

### ISSUE THREAD

**Issue by zmy20220416** [AstroNvim/astrocommunity#1214] opened 2024-09-20 09:38 UTC
### Checklist

- [X] I have searched through the AstroNvim documentation
- [X] I have searched through the existing issues of this project
- [X] I have searched the existing issues of plugins related to this issue
- [X] I can replicate the bug with the minimal `repro.lua` provided below

### Neovim version (nvim -v)

0.10.1

### Operating system/version

Windows 11

### Terminal/GUI

neovide

### Describe the bug

I updated to the latest version using the AstroUpdate command, and when I used grugfar.nvim again, all mappings were unavailable.

### Steps to Reproduce

1. open a file
2. <Leader>ss to open grugfar
3. Write Search and Replace, then go back to Normal Mode and press ,r, which did not replace as expected

### Expected behavior

The mapping is valid and the text of Search is replaced correctly.

### Screenshots

![bug](https://github.com/user-attachments/assets/e783305b-89a8-4bbe-9403-26dde188432b)

### Minimal configuration

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

-- install plugins
local plugins = {
  { "AstroNvim/AstroNvim", import = "astronvim.plugins" },
  { "AstroNvim/astrocommunity" },
  { import = "astrocommunity.search.grug-far-nvim" },

  -- add any other plugins/customizations here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- add anything else here (autocommands, vim.filetype, etc.)
```

**Comment by mehalter** [comment] 2024-09-20 11:48
Please follow the instructions in the issue form and add a minimal producing configuration

**Comment by mehalter** [comment] 2024-09-20 12:48
I modified the minimal reproducing configuration to be correct. Please note that in the future if issues are opened without it I will just close them as incomplete and reopen them once they get updated to be complete. The instructions are there to make sure that you can actually reproduce the bug and it's not just a problem with your own configuration. It also helps community members help you.


Thanks so much

**Comment by mehalter** [comment] 2024-09-20 12:48
That being said, I used the configuration above with the steps and all of the `grug-far.nvim` mappings work correctly. I used `,r` and it replaced totally fine. Marked this as cannot replicate.

**Comment by mehalter** [comment] 2024-09-20 20:49
Other users verified that it is working as intended. I'm going to go ahead and close this. If you can replicate it with a minimal configuration and can confirm it's an AstroCommunity issue and not just a bug in grug far then I can reopen this :)

**Closed by mehalter** 2024-09-20 20:49 UTC
Labels: bug, can't replicate
